name: E2E Test
description: "Runs candy sharing example notebook in specified kale version or local version and checks if the run succeeded"

on:
  workflow_dispatch:
    # temporary trigger for force the workflow to be registered
    push:
      branches:
        - local-e2e-test
    inputs:
      use-local-kale:
        required: false
        description: "Use the local kale version"
        default: "true"
      kale-installation-string:
        required: false
        description: "Installation string for kale, only used if use-local-kale is false (e.g. dev-kubeflow-kale or kubeflow-kale==0.7.0)"
        default: "kubeflow-kale"
      
env:
    USE_LOCAL_KALE: ${{ inputs.use-local-kale }}
    KALE_INSTALLATION_STRING: ${{ inputs.kale-installation-string }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.20.0
          cluster_name: kind-kale-test
    
      - name: Install KFP
        run: |
          export PIPELINE_VERSION=2.15.0
          kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
          kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
          kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=$PIPELINE_VERSION"
          sleep 10
      - name: Wait for KFP UI to be Ready
        run: |
          set -e
          
          kubectl rollout status deployment/ml-pipeline-ui -n kubeflow --timeout=10m
          kubectl rollout status deployment/ml-pipeline -n kubeflow --timeout=10m

      - name: Port Forward KFP (background)
        run: |
          nohup kubectl port-forward svc/ml-pipeline-ui 8080:80 -n kubeflow > /dev/null 2>&1 &
          sleep 5
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Libraries
        run: |                  
          python -m pip install --upgrade pip
          if [ "$USE_LOCAL_KALE" = "true" ]; then
            cd backend && pip install -e .[dev]
          else
            pip install $KALE_INSTALLATION_STRING
          fi
          echo "KALE_PIP_INDEX_URLS=https://test.pypi.org/simple" >> $GITHUB_ENV
          
      - name: Run example notebook
        run: |  
          kale --nb examples/base/candies_sharing.ipynb \
               --pipeline_name e2e-test \
               --pipeline_descr "E2E Test" 

          sed -i "s/'kubeflow-kale'/'dev-kubeflow-kale'/g" .kale/e2e-test.kale.py
          
          python3 .kale/e2e-test.kale.py

          python3 -c "
          import kfp
          client = kfp.Client(host='http://localhost:8080')
          client.create_run_from_pipeline_package(
              pipeline_file='auto_generated_pipeline.yaml',
              arguments={},
              run_name='e2e-test-run',
              experiment_name='e2e-test'
          )
          "

      - name: Check run result
        run: |
          python3 -c "

          import kfp, sys

          client = kfp.Client(host='http://localhost:8080')
          runs = client.list_runs(page_size=1).runs

          if not runs: sys.exit(1)

          run = client.wait_for_run_completion(runs[0].run_id, timeout=600)
          
          print(f'Pipeline run status: {run.state}')
          if run.state == 'SUCCEEDED':
            print('Pipeline run succeeded.')
            sys.exit(0)
          else:
            print(f'Pipeline run failed: {run.state}')
            sys.exit(1)
          "
      - name: Log from failed run
        if: failure()
        run: |
          echo "--- LOGS FROM FAILED STEPS ---"
          for pod in $(kubectl get pods -n kubeflow --field-selector=status.phase=Failed -o jsonpath='{.items[*].metadata.name}'); do
            echo "LOGS FOR POD: $pod "
            kubectl logs -n kubeflow $pod -c main || echo "Could not get logs for main container"
            
            echo "DESCRIBE POD: $pod "
            kubectl describe pod -n kubeflow $pod
          done  
